### ISSUE TITLE
Signature: antivirus_virustotal reporting ATT&CK Heuristics

### ISSUE THREAD

**Issue by phate1** [CybercentreCanada/assemblyline-service-cuckoo#102]
Hey

running cccs/assemblyline-service-cuckoo:4.0.0.stable47 (issue was present in previous versions)

I've noticed ATT&CK tags seem to be getting added to the 'Signature: antivirus_virustotal'  which doesn't seem to be right. I haven't had a chance to try and see how these are getting there yet, unfortunately.

![image](https://user-images.githubusercontent.com/1298031/125665080-17562e23-1981-43ba-b56a-a8564a2ccfe5.png)

**Comment by cccs-kevin** [comment]
Hey @phate1,

Thanks for reaching out!

You're right, there are not `ttp` (ATT&CK IDs) associated with that signature ([signature_link](https://github.com/cuckoosandbox/community/blob/14864b9fa2ba2576ca11887caf37616eaec6d941/modules/signatures/windows/antivirus_virustotal.py)) according to the raw signature. But this signature is mapped to the Assemblyline Heuristic `Anti-antivirus` which we've determined on the Assemblyline end should be linked to the ATT&CK IDs `T1518.001, T1562.001` ([heuristic_link](https://github.com/CybercentreCanada/assemblyline-service-cuckoo/blob/29b3e8c015b2304ca1e405b71ef9232bd2f4d4b7/service_manifest.yml#L216)).

What doesn't seem to be right about this?

**Comment by phate1** [comment]
Hey, thanks for the swift reply.
Sorry yes ignore the ATT&CK tags then so I guess my question is why is it tagging it anti-antivirus. as far as I'm aware that section simply pulls detections from VT so I don't think that gives it any indication that would suggest its anti-antivirus would it ?
I did check out virustotals page on the file and nothing there suggests it believes it demonstrates any behaviour that would result in that tag in case you were pulling more info from the API than I thought.

**Comment by cccs-kevin** [comment]
Ah, good point. I think this signature can be associated with a different heuristic then. @CCCS-MA thoughts?

**Comment by CCCS-MA** [comment]
I'm not certain we have a heuristic that currently fits the bill in this particular case. My suggestion would be to build one out.

**Comment by cccs-kevin** [comment]
Solution implemented in release [v4.0.0.stable48](https://github.com/CybercentreCanada/assemblyline-service-cuckoo/tree/v4.0.0.stable48)
