### ISSUE TITLE
Routing option is never passed to the Cuckoo API

### ISSUE THREAD

**Issue by Kerat** [CybercentreCanada/assemblyline-service-cuckoo#125]
Hello,
I found out that the routing option is never passed to the Cuckoo API, for example if I set the routing option to 'inetsim' into AL, the connector will submit the sample without the 'route' option which is necessary for set the network in the cuckoo sandbox.

A fix will be to add the route option to the 'task_options' object in the function _set_task_parameters (https://github.com/CybercentreCanada/assemblyline-service-cuckoo/blob/76e6313ea01f04c1e6006e950d28134be32e2f31/cuckoo/cuckoo_main.py#L1027)

**Comment by cccs-kevin** [comment]
Thanks for the ticket @Kerat! I'll start on a PR right away!

**Comment by Kerat** [comment]
You rock thank you
